name: Despliega a test

on:
    push:
        branches:
            -   develop

jobs:
  my-job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_test_secret.sh
        env:
          CLAVE_TEST: ${{ secrets.CLAVE_TEST }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cp $HOME/secrets/secret-test.json /var/www/html/
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: src/
          remote_path: /var/www/html/
          remote_host: 181.1.65.176
          remote_port: 22127
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_TEST_KEY }}
