name: Despliega a test

on:
    push:
        branches:
            -   develop

jobs:
  my-job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_test_secret.sh
        env:
          CLAVE_TEST: ${{ secrets.CLAVE_TEST }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/secret-test.json
