name: Despliega a prod

on:
    push:
        branches:
            -   main

jobs:
  my-job:
    name: Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_prod_secret.sh
        env:
          CLAVE_PROD: ${{ secrets.CLAVE_PROD }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cp $HOME/secrets/secret-prod.json src/
      - name: rsync web files
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: src/
          remote_path: /var/www/html/
          remote_host: 181.1.65.176
          remote_port: 22128
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_PROD_KEY }}
      - name: rsync config
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr
          path: conf/
          remote_path: /root
          remote_host: 181.1.65.176
          remote_port: 22128
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_PROD_KEY }}
